[module]
path = "example::explorer"

[dependencies]
"ecosystem::walkdir" = "0.1.0"
"ecosystem::notify" = "0.1.0"
"ecosystem::terminal" = "0.1.0"
"ecosystem::tui" = "0.1.0"
"ecosystem::ansi" = "0.1.0"
"ecosystem::color" = "0.1.0"
"ecosystem::progress" = "0.1.0"
"ecosystem::tui_markdown" = "0.1.0"
"ecosystem::tempfile" = "0.1.0"
